import { Nav } from "@/components/nav";
import { ResilienceLab } from "@/components/resilience-lab";
const stories=[
  ["Inference cold-start timeout","Decision service exceeded its deadline.","Fail closed before scheduling; health and timeout paths are explicit.","Run Decision Service Timeout in the lab."],
  ["Provider success, response lost","An external effect could exist while the worker saw a network failure.","Reconcile the stable provider idempotency key before any retry.","Run Success / Response Lost and inspect one provider effect."],
  ["Duplicate webhook delivery","At-least-once delivery repeated the same provider event.","Reserve the provider event ID transactionally after signature verification.","Run Duplicate Webhook ×10 and inspect duplicates blocked."],
  ["Stranded worker lease","A worker disappeared while durable work was claimed.","Lease expiry permits SKIP LOCKED reclamation by a new worker.","Run Expired Lease and inspect execution attempts."],
  ["Stale decision","Case state changed after a model produced a recommendation.","Compare case version at commit and again before execution.","Run Stale Decision and inspect suppression."],
] as const;
export default function Page(){return <><Nav/><main className="shell"><section className="pageIntro"><div className="eyebrow">RESILIENCE LAB</div><h1>Break it on purpose.<br/><em>Watch invariants hold.</em></h1><p>Development-only persisted fault experiments against the real authorization and worker boundary.</p></section><ResilienceLab/><section className="panel failureStories"><div className="panelTitle"><div><div className="eyebrow">WHAT BROKE · ROOT CAUSE · FIX · PROOF</div><h2>Reliability stories, not feature claims</h2></div><span>EXECUTABLE EVIDENCE</span></div><div>{stories.map(([title,broke,fix,proof])=><article key={title}><h3>{title}</h3><small>WHAT BROKE</small><p>{broke}</p><small>ROOT-CAUSE / FIX</small><p>{fix}</p><small>HOW TO PROVE IT</small><b>{proof}</b></article>)}</div><p className="scopeNote">Provider-response-loss evidence validates our reconciliation logic against a deterministic provider harness. It does not claim control over Razorpay network internals.</p></section></main></>}
