import { Nav } from "@/components/nav";import { backendJSON } from "@/lib/api";import { notFound } from "next/navigation";
type Row=Record<string,unknown>;
type Replay={case:Row;merchant:Row;events:Row[];decisions:Row[];candidates:Row[];economic_gates:Row[];policy_evaluations:Row[];actions:Row[];schedules:Row[];executions:Row[];promises_to_pay:Row[];attributions:Row[];provenance:Row};
const money=(value:unknown=0)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(Number(value)/100);const latest=<T,>(a:T[])=>a?.[a.length-1];
function JsonBlock({value}:{value:unknown}){return <pre>{JSON.stringify(value,null,2)}</pre>}
export default async function Page({params}:{params:Promise<{id:string}>}){const {id}=await params;const data=await backendJSON<Replay>(`/api/v1/recovery-cases/${id}/replay`);if(!data)notFound();const decision=latest(data.decisions);const selected=data.candidates.find(x=>x.action===decision?.selected_action);const gate=latest(data.economic_gates);const policy=latest(data.policy_evaluations);const execution=latest(data.executions);const attribution=latest(data.attributions);
return <><Nav/><main className="shell replay"><section className="replayHero"><div><div className="eyebrow">RECOVERY CASE REPLAY</div><h1>{money(data.case.amount_at_risk_minor)} <em>at risk</em></h1><p>{String(data.case.leak_type??"").replaceAll("_"," ")} · {String((data.case.failure_or_leak_context as Record<string,unknown>??{}).failure_category??"diagnosis recorded in context").replaceAll("_"," ")}</p><code>{id}</code></div><div className="stateBadge">{String(data.case.current_state??"").replaceAll("_"," ")}</div></section>
<section className="replayGrid"><article className="panel"><div className="step">01</div><div className="eyebrow">DETECTION & DIAGNOSIS</div><h2>Why recovery looked possible</h2><JsonBlock value={{leak:data.case.failure_or_leak_context,customer_snapshot:data.case.customer_context_snapshot}}/></article><article className="panel"><div className="step">02</div><div className="eyebrow">NEXT-BEST-ACTION</div><h2>{String(decision?.selected_action??"No decision yet").replaceAll("_"," ")}</h2><div className="decisionStats"><span>Action probability <b>{String(selected?.action_probability??"—")}</b></span><span>Natural probability <b>{String(selected?.natural_probability??"—")}</b></span><span>Incremental uplift <b>{String(selected?.incremental_uplift??"—")}</b></span><span>Predicted NERV <b>{money(Number(selected?.nerv_minor??0))}</b></span></div><details><summary>All ranked candidates</summary><JsonBlock value={data.candidates}/></details></article><article className="panel"><div className="step">03</div><div className="eyebrow">ECONOMICS & POLICY</div><h2>{String(gate?.decision??"Not evaluated")} · {String(policy?.result??policy?.decision??"Not evaluated")}</h2><p>{String(gate?.reason??"Economic justification awaits a decision.")}</p><JsonBlock value={{economic_gate:gate,policy_checks:policy?.checks,reason_codes:policy?.reason_codes}}/></article><article className="panel"><div className="step">04</div><div className="eyebrow">EXECUTION & OUTCOME</div><h2>{String(execution?.status??"No execution yet")}</h2><JsonBlock value={{schedule:latest(data.schedules),execution,promise:latest(data.promises_to_pay),attribution}}/><div className="attributionCallout"><small>ATTRIBUTION ANSWER</small><strong>{attribution?`${String(attribution.category).replaceAll("_"," ")} · ${attribution.rule_version}`:"No recovery attribution has been observed."}</strong></div></article></section>
<section className="panel timeline"><div className="panelTitle"><div><div className="eyebrow">IMMUTABLE AUDIT TRAIL</div><h2>The complete journey</h2></div><span>{data.events.length} events</span></div>{data.events.map((event,index)=><div className="event" key={String(event.id??index)}><i/><time>{String(event.occurred_at??event.timestamp??"")}</time><div><b>{String(event.event_type??event.type).replaceAll("_"," ")}</b><small>{String((event.actor as Record<string,unknown>)?.id??(event.actor as Record<string,unknown>)?.type??"system")}</small></div><code>#{String(event.sequence??index+1)}</code></div>)}</section><section className="provenance"><span>Decision provenance</span>{Object.entries(data.provenance).map(([key,value])=><code key={key}>{key}: {String(value)}</code>)}</section></main></>}
