"use client";
import Link from "next/link";
import { useEffect,useState } from "react";
import { publicBackend } from "@/lib/api";

type Row=Record<string,unknown>;type Replay={case:Row;decisions:Row[];economic_gates:Row[];policy_evaluations:Row[];human_reviews:Row[];schedules:Row[];executions:Row[];provider_references:Row[];webhook_events:Row[];attributions:Row[]};
const scenarios=[
 {id:"high_value_checkout",title:"₹8,999 High-value checkout",inject:"Checkout abandonment at payment",expect:"Payment Link wins → gate ALLOW → HIGH_VALUE_APPROVAL",proof:"AI choice, economics and bounded human authority"},
 {id:"checkout_abandonment",title:"Checkout abandonment",inject:"₹2,499 payment-friction abandonment",expect:"Real detection and next-best-action evaluation",proof:"Checkout revenue-risk detection"},
 {id:"payment_failure",title:"Payment failure",inject:"₹1,299 insufficient-funds failure",expect:"Subscription-style risk and recovery decision",proof:"Payment failure detection"},
 {id:"active_promise",title:"Active Promise-to-Pay",inject:"Failure plus a customer promise due tomorrow",expect:"Contact/retry interventions are bounded",proof:"Stopping rules prevent customer spam"},
 {id:"low_value",title:"Economically unviable",inject:"₹5 low-value payment failure",expect:"Economic gate blocks wasteful intervention",proof:"Incremental-value discipline"},
];
const eventLabels=["Risk detected","AI decision completed","Economic gate passed","Policy evaluated","Human approval","Action scheduled","Razorpay link created","Payment observed","Revenue attributed","Case recovered"];
export function ScenarioLab(){const[busy,setBusy]=useState(""),[error,setError]=useState(""),[caseID,setCaseID]=useState(""),[replay,setReplay]=useState<Replay|null>(null);
useEffect(()=>{if(!caseID)return;const load=()=>fetch(`${publicBackend}/api/v1/recovery-cases/${caseID}/replay`).then(r=>r.ok?r.json():null).then(setReplay).catch(()=>{});load();const timer=setInterval(load,3000);return()=>clearInterval(timer)},[caseID]);
async function create(id:string){setBusy(id);setError("");try{const r=await fetch(`${publicBackend}/api/v1/demo/scenarios/${id}`,{method:"POST"});const b=await r.json();if(!r.ok)throw new Error(b?.error?.message??b?.error??"Scenario failed");setCaseID(b.case.case_id);setReplay(null)}catch(e){setError(e instanceof Error?e.message:"Scenario failed")}finally{setBusy("")}}
const link=(replay?.provider_references??[]).map(x=>x.response as Row).find(x=>typeof x?.short_url==="string")?.short_url as string|undefined;const state=String(replay?.case?.current_state??"");const steps=[!!replay,(replay?.decisions?.length??0)>0,String(replay?.economic_gates?.at(-1)?.result??"")==="ALLOW",(replay?.policy_evaluations?.length??0)>0,(replay?.human_reviews?.length??0)>0,(replay?.schedules?.length??0)>0,(replay?.executions?.length??0)>0,(replay?.webhook_events?.some(x=>x.event_type==="payment_link.paid")??false),(replay?.attributions?.length??0)>0,state==="RECOVERED"];
return <><section className="scenarioCards">{scenarios.map(s=><article className="panel" key={s.id}><div className="dataMode">LIVE OPERATIONAL · SYNTHETIC INPUT</div><h2>{s.title}</h2><dl><dt>Injects</dt><dd>{s.inject}</dd><dt>Expected</dt><dd>{s.expect}</dd><dt>Demonstrates</dt><dd>{s.proof}</dd></dl><button onClick={()=>create(s.id)} disabled={!!busy}>{busy===s.id?"Running real workflow…":"Create & run decision"}</button></article>)}</section>{error&&<div className="error panel">{error}</div>}
{caseID&&<section className="panel guided"><div className="panelTitle"><div><div className="eyebrow">GUIDED LIVE JOURNEY</div><h2>{caseID}</h2></div><Link href={`/recovery/${caseID}`}>Open full case →</Link></div><div className="progressGrid">{eventLabels.map((label,i)=><span className={steps[i]?"done":"waiting"} key={label}><i>{steps[i]?"✓":i+1}</i><b>{label}</b></span>)}</div>{state==="ESCALATED"&&<div className="notice">Human approval is required. Open <Link href="/operations">Operations</Link>, approve this case, then return here—the progress updates automatically.</div>}{link&&state!=="RECOVERED"&&<a className="paymentButton" href={link} target="_blank" rel="noreferrer">Open Razorpay Test Payment <small>TEST MODE · NO REAL MONEY</small></a>}{state==="RECOVERED"&&<div className="recoveredBanner"><b>PAYMENT OBSERVED · REVENUE RECOVERED</b><span>Strong attribution is available in the case evidence.</span></div>}</section>}
</>}
