-- Deterministic, idempotent Test Mode fixture. Never contains real contact data.
INSERT INTO merchants(id,name,merchant_type,metadata) VALUES('demo-merchant-v1','Demo SaaS Merchant','SAAS','{"fixture":true}') ON CONFLICT DO NOTHING;
INSERT INTO merchant_policies(id,merchant_id,objective,max_retries,max_contacts_per_day,max_contacts_per_week,min_contact_interval_minutes,recovery_window_hours,quiet_hours,allowed_actions,allowed_channels,high_value_threshold_minor,low_confidence_threshold,minimum_economic_value_minor,maximum_incentive_minor,requires_high_value_human_approval,version) VALUES('demo-policy-v1','demo-merchant-v1','BALANCED',3,2,5,60,336,'{}',ARRAY['WAIT','RETRY_LATER','SEND_PAYMENT_LINK','SEND_REMINDER'],ARRAY['EMAIL'],500000,0.55,1000,0,true,1) ON CONFLICT DO NOTHING;
INSERT INTO customers(id,merchant_id,external_id,contact,opted_out) VALUES('demo-customer-v1','demo-merchant-v1','safe-demo-customer','{"reference":"masked"}',false) ON CONFLICT DO NOTHING;
INSERT INTO customer_recovery_profiles(id,customer_id,successful_payments,failed_payments,subscription_tenure_days,promise_reliability,fatigue_score,features,version) VALUES('demo-profile-v1','demo-customer-v1',12,2,420,.8,.1,'{}',1) ON CONFLICT DO NOTHING;

INSERT INTO recovery_cases(id,leak_type,merchant_id,customer_id,amount_at_risk_minor,currency,source_reference,source_status,failure_or_leak_context,customer_context_snapshot,merchant_policy_snapshot,current_state,recovery_deadline,recovered_amount_minor,attribution_status,version,created_at,updated_at) VALUES
('demo-recovered-case-v1','FAILED_SUBSCRIPTION','demo-merchant-v1','demo-customer-v1',249900,'INR','demo-recovered-source-v1','PAID','{"failure_type":"TEMPORARY_BANK_FAILURE"}','{}','{"version":1}','RECOVERED','2035-01-01T00:00:00Z',249900,'AGENT_ATTRIBUTED',9,'2026-09-01T10:00:00Z','2026-09-01T10:20:00Z'),
('demo-ptp-case-v1','FAILED_SUBSCRIPTION','demo-merchant-v1','demo-customer-v1',129900,'INR','demo-ptp-source-v1','FAILED','{"failure_type":"INSUFFICIENT_FUNDS"}','{}','{"version":1}','WAITING_OUTCOME','2035-01-01T00:00:00Z',0,'PENDING',7,'2026-09-01T11:00:00Z','2026-09-01T11:20:00Z'),
('demo-escalated-case-v1','CHECKOUT_ABANDONMENT','demo-merchant-v1','demo-customer-v1',899900,'INR','demo-escalated-source-v1','ABANDONED','{"failure_type":"PRICE_HESITATION"}','{}','{"version":1}','ESCALATED','2035-01-01T00:00:00Z',0,'PENDING',4,'2026-09-01T12:00:00Z','2026-09-01T12:10:00Z') ON CONFLICT DO NOTHING;

INSERT INTO recovery_decisions(id,case_id,case_version,optimizer_version,merchant_objective,context_version,outcome_model_version,natural_model_version,cost_model_version,selected_action,selected_nerv_minor,created_at) VALUES('demo-decision-escalated-v1','demo-escalated-case-v1',3,'nba-v1','BALANCED','recovery-context-v1','outcome-v1','natural-recovery-v1','cost-v1','SEND_PAYMENT_LINK',196000,'2026-09-01T12:08:00Z') ON CONFLICT DO NOTHING;
INSERT INTO recovery_decision_candidates(id,decision_id,action,action_probability,natural_probability,incremental_uplift,gross_incremental_value_minor,channel_cost_minor,incentive_cost_minor,operational_cost_minor,fatigue_penalty_minor,risk_penalty_minor,nerv_minor,objective_score_minor,ranking_position,reason_codes) VALUES('demo-candidate-escalated-v1','demo-decision-escalated-v1','SEND_PAYMENT_LINK',.42,.18,.24,215976,500,0,500,4000,14976,196000,196000,1,ARRAY['HIGHEST_EXPECTED_NERV']) ON CONFLICT DO NOTHING;
INSERT INTO economic_gate_evaluations(id,decision_id,case_id,action,nerv_minor,threshold_minor,result,reason_code,gate_version,created_at) VALUES('demo-gate-escalated-v1','demo-decision-escalated-v1','demo-escalated-case-v1','SEND_PAYMENT_LINK',196000,1000,'ALLOW','POSITIVE_EXPECTED_VALUE','economic-gate-v1','2026-09-01T12:08:01Z') ON CONFLICT DO NOTHING;
INSERT INTO policy_evaluations(id,decision_id,economic_gate_id,case_id,case_version,selected_action,policy_version,result,reason_codes,checks,created_at) VALUES('demo-policy-eval-escalated-v1','demo-decision-escalated-v1','demo-gate-escalated-v1','demo-escalated-case-v1',3,'SEND_PAYMENT_LINK','policy-v1','ESCALATE',ARRAY['HIGH_VALUE_APPROVAL'],'{"HIGH_VALUE_APPROVAL":false}','2026-09-01T12:08:02Z') ON CONFLICT DO NOTHING;

INSERT INTO customer_responses(id,case_id,response_type,payload,source,received_at,correlation_id) VALUES('demo-response-v1','demo-ptp-case-v1','PROMISE_TO_PAY','{"safe_fixture":true}','DEMO','2026-09-01T11:20:00Z','demo-ptp-response-v1') ON CONFLICT DO NOTHING;
INSERT INTO promises_to_pay(id,case_id,customer_id,status,due_at,confidence,source,created_at,promised_amount_minor,extractor_version,extraction_timestamp,source_response_id) VALUES('demo-promise-v1','demo-ptp-case-v1','demo-customer-v1','ACTIVE','2034-12-30T00:00:00Z',.9,'{"channel":"EMAIL","fixture":true}','2026-09-01T11:20:00Z',129900,'ptp-extractor-v1','2026-09-01T11:20:00Z','demo-response-v1') ON CONFLICT DO NOTHING;

INSERT INTO recovery_events(id,case_id,sequence,event_type,occurred_at,actor,payload,model_version,correlation_id) VALUES
('demo-event-r1','demo-recovered-case-v1',1,'CASE_CREATED','2026-09-01T10:00:00Z','{"type":"SYSTEM","id":"demo-seed"}','{"state":"DETECTED"}',NULL,'demo-recovered-v1'),
('demo-event-r2','demo-recovered-case-v1',2,'ACTION_SELECTED','2026-09-01T10:05:00Z','{"type":"SYSTEM","id":"nba-v1"}','{"action":"RETRY_LATER"}','outcome-v1','demo-recovered-v1'),
('demo-event-r3','demo-recovered-case-v1',3,'RECOVERY_COMPLETED','2026-09-01T10:20:00Z','{"type":"SYSTEM","id":"observer"}','{"amount_minor":249900}',NULL,'demo-recovered-v1'),
('demo-event-p1','demo-ptp-case-v1',1,'CASE_CREATED','2026-09-01T11:00:00Z','{"type":"SYSTEM","id":"demo-seed"}','{"state":"DETECTED"}',NULL,'demo-ptp-v1'),
('demo-event-p2','demo-ptp-case-v1',2,'PROMISE_CREATED','2026-09-01T11:20:00Z','{"type":"CUSTOMER","id":"safe-demo-customer"}','{"promise_id":"demo-promise-v1"}',NULL,'demo-ptp-v1'),
('demo-event-e1','demo-escalated-case-v1',1,'CASE_CREATED','2026-09-01T12:00:00Z','{"type":"SYSTEM","id":"demo-seed"}','{"state":"DETECTED"}',NULL,'demo-escalated-v1'),
('demo-event-e2','demo-escalated-case-v1',2,'ACTION_SELECTED','2026-09-01T12:08:00Z','{"type":"SYSTEM","id":"nba-v1"}','{"action":"SEND_PAYMENT_LINK"}','outcome-v1','demo-escalated-v1'),
('demo-event-e3','demo-escalated-case-v1',3,'POLICY_ESCALATED','2026-09-01T12:08:02Z','{"type":"POLICY","id":"policy-v1"}','{"reason_codes":["HIGH_VALUE_APPROVAL"]}',NULL,'demo-escalated-v1'),
('demo-event-e4','demo-escalated-case-v1',4,'HUMAN_REVIEW_REQUESTED','2026-09-01T12:08:03Z','{"type":"SYSTEM","id":"operations"}','{"priority":"CRITICAL"}',NULL,'demo-escalated-v1') ON CONFLICT DO NOTHING;
