DROP TRIGGER IF EXISTS policy_evaluations_immutable ON policy_evaluations;
DROP TRIGGER IF EXISTS economic_gates_immutable ON economic_gate_evaluations;
DROP TRIGGER IF EXISTS decision_candidates_immutable ON recovery_decision_candidates;
DROP TRIGGER IF EXISTS decisions_immutable ON recovery_decisions;
DROP TRIGGER IF EXISTS natural_predictions_immutable ON natural_recovery_predictions;
DROP FUNCTION IF EXISTS reject_append_only_mutation();
DROP TABLE IF EXISTS customer_responses;
DROP TABLE IF EXISTS retry_requests;
DROP TABLE IF EXISTS email_deliveries;
DROP INDEX IF EXISTS executions_idempotency_idx;
ALTER TABLE executions DROP COLUMN IF EXISTS retryable,DROP COLUMN IF EXISTS failure_class,DROP COLUMN IF EXISTS idempotency_key,DROP COLUMN IF EXISTS scheduled_action_id;
DROP TABLE IF EXISTS scheduled_actions;
DROP TABLE IF EXISTS policy_evaluations;
DROP TABLE IF EXISTS economic_gate_evaluations;
DROP TABLE IF EXISTS recovery_decision_candidates;
DROP TABLE IF EXISTS recovery_decisions;
DROP TABLE IF EXISTS natural_recovery_predictions;
ALTER TABLE action_predictions DROP COLUMN IF EXISTS natural_model_version,DROP COLUMN IF EXISTS context_version,DROP COLUMN IF EXISTS case_version;
UPDATE platform_metadata SET value='phase_10' WHERE key='schema_version';
