DROP TRIGGER IF EXISTS allocations_immutable ON budget_allocations;
DROP TRIGGER IF EXISTS allocation_runs_immutable ON budget_allocation_runs;
DROP TRIGGER IF EXISTS priorities_immutable ON portfolio_priority_snapshots;
DROP TRIGGER IF EXISTS model_status_immutable ON model_registry_status_events;
DROP TRIGGER IF EXISTS model_entries_immutable ON model_registry_entries;
DROP TRIGGER IF EXISTS datasets_immutable ON training_dataset_versions;
DROP TRIGGER IF EXISTS feedback_immutable ON feedback_records;
DROP TRIGGER IF EXISTS attributions_immutable ON recovery_attributions;
DROP TRIGGER IF EXISTS merchant_profiles_immutable ON merchant_optimization_profiles;
DROP TRIGGER IF EXISTS promise_events_immutable ON promise_events;
DROP TABLE IF EXISTS budget_allocations;
DROP TABLE IF EXISTS budget_allocation_runs;
DROP TABLE IF EXISTS portfolio_priority_snapshots;
DROP TABLE IF EXISTS model_registry_status_events;
DROP TABLE IF EXISTS model_registry_entries;
DROP TABLE IF EXISTS training_dataset_versions;
DROP TABLE IF EXISTS feedback_records;
DROP TABLE IF EXISTS recovery_attributions;
DROP TABLE IF EXISTS attribution_rule_configs;
ALTER TABLE recovery_decisions DROP COLUMN IF EXISTS merchant_profile_snapshot,DROP COLUMN IF EXISTS merchant_profile_version,DROP COLUMN IF EXISTS merchant_profile_id;
DROP TABLE IF EXISTS merchant_optimization_profiles;
DROP TABLE IF EXISTS promise_checks;
DROP TABLE IF EXISTS promise_events;
DROP INDEX IF EXISTS promises_source_response_idx;
ALTER TABLE promises_to_pay DROP COLUMN IF EXISTS verification_reference,DROP COLUMN IF EXISTS cancelled_at,DROP COLUMN IF EXISTS expired_at,DROP COLUMN IF EXISTS broken_at,DROP COLUMN IF EXISTS fulfilled_at,DROP COLUMN IF EXISTS source_response_id,DROP COLUMN IF EXISTS extraction_timestamp,DROP COLUMN IF EXISTS extractor_version,DROP COLUMN IF EXISTS promised_amount_minor;
UPDATE platform_metadata SET value='phase_16.1' WHERE key='schema_version';
